dist: xenial # Ubuntu 16.04
language: bash
branches:
only:
  - main
before_install:
  - wget https://releases.hashicorp.com/terraform/0.14.0/terraform_0.14.0_linux_amd64.zip
  - unzip terraform_terraform_0.14.0_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_terraform_0.14.0_linux_amd64.zip
jobs:
  include:
    - stage: terraform plan
      # Only run terraform validate and plan state if within a pull request
      if: type IN (pull_request)
      script:
        - echo "Executing Terraform Plan on pull request code"
        - terraform init 
        - terraform validate 
        - terraform plan 
    - stage: terraform apply
      # Only run terraform apply stage if outside of a pull request
      if: type IN (push) and branch = main
      script:
        - echo "Executing Terraform Apply on merged code"
        - terraform init 
        - terraform apply
